project:
  type: website
  output-dir: docs

website:
  title: "CSIDS"
  body-header: <script data-goatcounter="https://csidsno.goatcounter.com/count" async src="//gc.zgo.at/count.js"></script>
  favicon: favicon.png
  navbar:
    title: false
    logo: "resources/logo/logo_full_white.png"
    right:
      - text: "Home"
        href: index.qmd
      - text: "Packages"
        menu:
        - text: "Introduction"
          href: packages_intro.qmd
        - text: -------
        - text: attrib
          href: https://www.csids.no/attrib/
        - text: csalert
          href: https://www.csids.no/csalert/
        - text: csdata
          href: https://www.csids.no/csdata/
        - text: csdb
          href: https://www.csids.no/csdb/
        - text: csmaps
          href: https://www.csids.no/csmaps/
        - text: cstidy
          href: https://www.csids.no/cstidy/
        - text: cstime
          href: https://www.csids.no/cstime/
        - text: csutil
          href: https://www.csids.no/csutil/
        - text: org
          href: https://www.csids.no/org/
        - text: plnr
          href: https://www.csids.no/plnr/
        - text: respiranor
          href: https://www.csids.no/respiranor/

        #- text: csstyle
        #  href: https://www.csids.no/csstyle/
        - text: sc9
          href: https://www.csids.no/sc9/
#      - blog.qmd
      - text: "About"
        menu:
        - text: "About CSIDS"
          href: about_csids.qmd
        - text: "Get involved"
          href: about_get_involved.qmd


      - icon: github
        href: https://github.com/csids
format:
  html:
    css: styles.css
    include-after-body: footer.html


