project:
  type: website
  output-dir: docs


website:
  title: "CSIDS"
  favicon: favicon.png
  navbar:
    right:
      - text: "Home"
        href: index.html
      - text: "Packages"
        href: packages.html
      - text: "Resources"
        href: resources.html
#      - blog.qmd
      - icon: github
        href: https://github.com/csids
format:
  html:
    theme: journal
    # css: styles.css
    title-block-banner: "#b8e2f2"
    title-block-banner-color: "#000000"



