---
title: "Members"
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = FALSE)
```

**Calvin Chiang** is a experienced engineer with 10 years of industry experience. Calvin is working on the IT infrastructure.

**Chi Zhang** has submitted her PhD thesis on hospital Electronic Health Records representation and utilization at the University of Oslo. She has a MSc in Statistics from Imperial College London. Since Chi joined FHI in 2020, she has been working on the R-packages splverse that are key to the Sykdomspulsen infrastructure. Chi is responsible for NorMOMO (excess mortality surveillance in Norway). You can find Chi on [Twitter](https://twitter.com/Andreasheenn)

**Gry Marysol Grøneng** is the project leader of Sykdomspulsen. She is a veterinarian with a PhD in Epidemiology. She has worked with surveillance of infectious diseases since 2015.

**Richard Aubrey White** completed his PhD in Biostatistics at Harvard University. He has previously worked on outbreaks/surveillance projects in Sierra Leone (Ebola), Mozambique (cholera), and Palestine (maternal health). He now works primarily on the infrastructure Sykdomspulsen Core and the R-package plnr.
